// <auto-generated />
using System;
using GPS.API.Data.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GPS.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241125163142_New")]
    partial class New
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GPS.API.Data.Models.Bus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Capacity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManufactureYear")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenantId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Buses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = "20",
                            ManufactureYear = "2002",
                            Manufacturer = "MAN",
                            Model = "MK2",
                            RegistrationNumber = "12345678",
                            TenantId = "mostar"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = "21",
                            ManufactureYear = "2003",
                            Manufacturer = "MAN",
                            Model = "MK3",
                            RegistrationNumber = "asd5678",
                            TenantId = "sarajevo"
                        });
                });

            modelBuilder.Entity("GPS.API.Data.Models.CreditCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CCV")
                        .HasColumnType("int");

                    b.Property<string>("CardName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExpirationDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenantId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CreditCards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CCV = 123,
                            CardName = "Faris",
                            CardNumber = "1234 5679 8791",
                            ExpirationDate = "7/28",
                            TenantId = "mostar"
                        },
                        new
                        {
                            Id = 2,
                            CCV = 254,
                            CardName = "Nedim",
                            CardNumber = "2432 4454 4545",
                            ExpirationDate = "7/28",
                            TenantId = "sarajevo"
                        });
                });

            modelBuilder.Entity("GPS.API.Data.Models.Discount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiscountName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("DiscountValue")
                        .HasColumnType("real");

                    b.Property<string>("TenantId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Discounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DiscountName = "Student",
                            DiscountValue = 0.15f,
                            TenantId = "mostar"
                        },
                        new
                        {
                            Id = 2,
                            DiscountName = "Penzioner",
                            DiscountValue = 0.17f,
                            TenantId = "sarajevo"
                        });
                });

            modelBuilder.Entity("GPS.API.Data.Models.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("Picture")
                        .HasColumnType("varbinary(max)");

                    b.Property<float>("Rating")
                        .HasColumnType("real");

                    b.Property<string>("TenantId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Feedbacks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5f,
                            TenantId = "mostar",
                            UserId = 5
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 3f,
                            TenantId = "mostar",
                            UserId = 6
                        });
                });

            modelBuilder.Entity("GPS.API.Data.Models.Line", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompleteDistance")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EndingStationId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StartingStationId")
                        .HasColumnType("int");

                    b.Property<string>("TenantId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EndingStationId");

                    b.HasIndex("StartingStationId");

                    b.ToTable("Lines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompleteDistance = "10",
                            EndingStationId = 1,
                            IsActive = true,
                            Name = "21",
                            StartingStationId = 2,
                            TenantId = "mostar"
                        },
                        new
                        {
                            Id = 2,
                            CompleteDistance = "10",
                            EndingStationId = 1,
                            IsActive = true,
                            Name = "21",
                            StartingStationId = 2,
                            TenantId = "mostar"
                        });
                });

            modelBuilder.Entity("GPS.API.Data.Models.MyAppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime?>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("TenantId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MyAppUsers", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("GPS.API.Data.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("Duration")
                        .HasColumnType("time");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("LineId")
                        .HasColumnType("int");

                    b.Property<int>("NotificationTypeId")
                        .HasColumnType("int");

                    b.Property<string>("TenantId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LineId");

                    b.HasIndex("NotificationTypeId");

                    b.ToTable("Notifications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateOnly(2024, 1, 1),
                            Duration = new TimeOnly(1, 1, 1),
                            IsActive = true,
                            LineId = 1,
                            NotificationTypeId = 1,
                            TenantId = "mostar"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateOnly(2024, 1, 1),
                            Duration = new TimeOnly(1, 1, 1),
                            IsActive = true,
                            LineId = 2,
                            NotificationTypeId = 2,
                            TenantId = "mostar"
                        });
                });

            modelBuilder.Entity("GPS.API.Data.Models.NotificationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenantId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NotificationTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A warning notif",
                            Name = "Warning",
                            TenantId = "mostar"
                        },
                        new
                        {
                            Id = 2,
                            Description = "A error notif",
                            Name = "Error",
                            TenantId = "mostar"
                        });
                });

            modelBuilder.Entity("GPS.API.Data.Models.PassengerCreditCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreditCardId")
                        .HasColumnType("int");

                    b.Property<int>("PassengerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SavingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenantId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreditCardId");

                    b.HasIndex("PassengerId");

                    b.ToTable("PassengerCreditCards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreditCardId = 1,
                            PassengerId = 5,
                            SavingDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenantId = "mostar"
                        },
                        new
                        {
                            Id = 2,
                            CreditCardId = 2,
                            PassengerId = 6,
                            SavingDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenantId = "sarajevo"
                        });
                });

            modelBuilder.Entity("GPS.API.Data.Models.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("DistanceFromTheNextStation")
                        .HasColumnType("real");

                    b.Property<int>("LineId")
                        .HasColumnType("int");

                    b.Property<int>("StationId")
                        .HasColumnType("int");

                    b.Property<string>("TenantId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LineId");

                    b.HasIndex("StationId");

                    b.ToTable("Routes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DistanceFromTheNextStation = 15.6f,
                            LineId = 1,
                            StationId = 1,
                            TenantId = "mostar"
                        },
                        new
                        {
                            Id = 2,
                            DistanceFromTheNextStation = 15.6f,
                            LineId = 2,
                            StationId = 2,
                            TenantId = "mostar"
                        });
                });

            modelBuilder.Entity("GPS.API.Data.Models.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly>("DepartureTime")
                        .HasColumnType("time");

                    b.Property<int>("LineId")
                        .HasColumnType("int");

                    b.Property<string>("TenantId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LineId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("GPS.API.Data.Models.Shift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BusId")
                        .HasColumnType("int");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ShiftDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("ShiftEndingTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("ShiftStartingTime")
                        .HasColumnType("time");

                    b.Property<string>("TenantId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BusId");

                    b.HasIndex("DriverId");

                    b.ToTable("Shifts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BusId = 1,
                            DriverId = 1,
                            ShiftDate = new DateOnly(2024, 1, 1),
                            ShiftEndingTime = new TimeOnly(16, 0, 0),
                            ShiftStartingTime = new TimeOnly(8, 0, 0),
                            TenantId = "mostar"
                        },
                        new
                        {
                            Id = 2,
                            BusId = 2,
                            DriverId = 2,
                            ShiftDate = new DateOnly(2024, 1, 1),
                            ShiftEndingTime = new TimeOnly(16, 0, 0),
                            ShiftStartingTime = new TimeOnly(8, 0, 0),
                            TenantId = "mostar"
                        });
                });

            modelBuilder.Entity("GPS.API.Data.Models.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GPSCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenantId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ZoneId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ZoneId");

                    b.ToTable("Stations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GPSCode = "6.6.6",
                            Location = "Bafo",
                            Name = "Bafo",
                            TenantId = "mostar",
                            ZoneId = 1
                        },
                        new
                        {
                            Id = 2,
                            GPSCode = "13123",
                            Location = "Sutina",
                            Name = "Sutina1",
                            TenantId = "sarajevo",
                            ZoneId = 2
                        });
                });

            modelBuilder.Entity("GPS.API.Data.Models.SystemActionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ExceptionMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAdress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsException")
                        .HasColumnType("bit");

                    b.Property<string>("PostData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QueryPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeOfAction")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SystemActionsLog");
                });

            modelBuilder.Entity("GPS.API.Data.Models.Tenant", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tenants");

                    b.HasData(
                        new
                        {
                            Id = "mostar",
                            Name = "MostarBus"
                        },
                        new
                        {
                            Id = "sarajevo",
                            Name = "Sarajevo"
                        },
                        new
                        {
                            Id = "bugojno",
                            Name = "Bugojno"
                        });
                });

            modelBuilder.Entity("GPS.API.Data.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LineId")
                        .HasColumnType("int");

                    b.Property<byte[]>("QrCode")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("TenantId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TicketTypeId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ZoneId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LineId");

                    b.HasIndex("TicketTypeId");

                    b.HasIndex("UserId");

                    b.HasIndex("ZoneId");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpirationDate = new DateTime(2024, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LineId = 1,
                            QrCode = new byte[0],
                            TenantId = "mostar",
                            TicketTypeId = 1,
                            UserId = 2,
                            ZoneId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpirationDate = new DateTime(2024, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LineId = 2,
                            QrCode = new byte[0],
                            TenantId = "mostar",
                            TicketTypeId = 2,
                            UserId = 1,
                            ZoneId = 1
                        });
                });

            modelBuilder.Entity("GPS.API.Data.Models.TicketType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenantId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TicketTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Basic",
                            TenantId = "mostar"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Advanced",
                            TenantId = "mostar"
                        });
                });

            modelBuilder.Entity("GPS.API.Data.Models.Zone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TenantId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Zones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Zone one",
                            Price = 1.5m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Zone two",
                            Price = 2.1m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Zone three",
                            Price = 2.7m
                        });
                });

            modelBuilder.Entity("GPS.API.Data.Models.Driver", b =>
                {
                    b.HasBaseType("GPS.API.Data.Models.MyAppUser");

                    b.Property<string>("DriversLicenseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("License")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("WorkingHoursInAWeek")
                        .HasColumnType("real");

                    b.ToTable("Drivers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "1",
                            FirstName = "Adi",
                            LastName = "Gosto",
                            PasswordHash = new byte[] { 129, 239, 116, 26, 24, 102, 142, 194, 211, 49, 217, 207, 174, 123, 16, 237, 66, 195, 220, 119, 252, 39, 69, 15, 144, 124, 205, 16, 48, 150, 142, 35, 214, 217, 107, 175, 28, 38, 106, 76, 192, 179, 91, 14, 26, 5, 32, 80, 38, 247, 163, 124, 13, 130, 118, 90, 10, 214, 137, 189, 22, 241, 115, 49 },
                            PasswordSalt = new byte[] { 98, 172, 48, 116, 95, 203, 108, 1, 224, 199, 159, 129, 67, 46, 182, 136, 135, 198, 175, 247, 201, 53, 252, 123, 71, 147, 16, 112, 233, 11, 200, 201, 177, 173, 228, 141, 247, 166, 137, 19, 80, 64, 24, 235, 239, 140, 209, 171, 50, 67, 26, 43, 80, 69, 166, 148, 95, 129, 7, 240, 18, 133, 43, 33, 97, 55, 142, 184, 8, 123, 8, 169, 106, 216, 190, 27, 235, 105, 186, 234, 186, 35, 213, 55, 129, 102, 79, 201, 236, 125, 41, 11, 64, 120, 228, 95, 7, 164, 254, 143, 190, 114, 138, 53, 106, 200, 56, 79, 86, 96, 104, 109, 142, 181, 83, 33, 89, 193, 65, 14, 59, 87, 158, 243, 69, 106, 195, 201 },
                            TenantId = "mostar",
                            DriversLicenseNumber = "a1435affaa",
                            HireDate = new DateTime(2024, 11, 25, 17, 31, 42, 135, DateTimeKind.Local).AddTicks(6194),
                            License = "1123123"
                        },
                        new
                        {
                            Id = 2,
                            Email = "2",
                            FirstName = "Nedim",
                            LastName = "Jugo",
                            PasswordHash = new byte[] { 129, 239, 116, 26, 24, 102, 142, 194, 211, 49, 217, 207, 174, 123, 16, 237, 66, 195, 220, 119, 252, 39, 69, 15, 144, 124, 205, 16, 48, 150, 142, 35, 214, 217, 107, 175, 28, 38, 106, 76, 192, 179, 91, 14, 26, 5, 32, 80, 38, 247, 163, 124, 13, 130, 118, 90, 10, 214, 137, 189, 22, 241, 115, 49 },
                            PasswordSalt = new byte[] { 98, 172, 48, 116, 95, 203, 108, 1, 224, 199, 159, 129, 67, 46, 182, 136, 135, 198, 175, 247, 201, 53, 252, 123, 71, 147, 16, 112, 233, 11, 200, 201, 177, 173, 228, 141, 247, 166, 137, 19, 80, 64, 24, 235, 239, 140, 209, 171, 50, 67, 26, 43, 80, 69, 166, 148, 95, 129, 7, 240, 18, 133, 43, 33, 97, 55, 142, 184, 8, 123, 8, 169, 106, 216, 190, 27, 235, 105, 186, 234, 186, 35, 213, 55, 129, 102, 79, 201, 236, 125, 41, 11, 64, 120, 228, 95, 7, 164, 254, 143, 190, 114, 138, 53, 106, 200, 56, 79, 86, 96, 104, 109, 142, 181, 83, 33, 89, 193, 65, 14, 59, 87, 158, 243, 69, 106, 195, 201 },
                            TenantId = "sarajevo",
                            DriversLicenseNumber = "adasd43aa",
                            HireDate = new DateTime(2024, 11, 25, 17, 31, 42, 137, DateTimeKind.Local).AddTicks(8318),
                            License = "11jdfghsdjg23"
                        });
                });

            modelBuilder.Entity("GPS.API.Data.Models.Manager", b =>
                {
                    b.HasBaseType("GPS.API.Data.Models.MyAppUser");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ManagerLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Managers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 3,
                            Email = "3",
                            FirstName = "Adil",
                            LastName = "Joldic",
                            PasswordHash = new byte[] { 129, 239, 116, 26, 24, 102, 142, 194, 211, 49, 217, 207, 174, 123, 16, 237, 66, 195, 220, 119, 252, 39, 69, 15, 144, 124, 205, 16, 48, 150, 142, 35, 214, 217, 107, 175, 28, 38, 106, 76, 192, 179, 91, 14, 26, 5, 32, 80, 38, 247, 163, 124, 13, 130, 118, 90, 10, 214, 137, 189, 22, 241, 115, 49 },
                            PasswordSalt = new byte[] { 98, 172, 48, 116, 95, 203, 108, 1, 224, 199, 159, 129, 67, 46, 182, 136, 135, 198, 175, 247, 201, 53, 252, 123, 71, 147, 16, 112, 233, 11, 200, 201, 177, 173, 228, 141, 247, 166, 137, 19, 80, 64, 24, 235, 239, 140, 209, 171, 50, 67, 26, 43, 80, 69, 166, 148, 95, 129, 7, 240, 18, 133, 43, 33, 97, 55, 142, 184, 8, 123, 8, 169, 106, 216, 190, 27, 235, 105, 186, 234, 186, 35, 213, 55, 129, 102, 79, 201, 236, 125, 41, 11, 64, 120, 228, 95, 7, 164, 254, 143, 190, 114, 138, 53, 106, 200, 56, 79, 86, 96, 104, 109, 142, 181, 83, 33, 89, 193, 65, 14, 59, 87, 158, 243, 69, 106, 195, 201 },
                            TenantId = "mostar",
                            Department = "HR",
                            HireDate = new DateTime(2024, 11, 25, 17, 31, 42, 137, DateTimeKind.Local).AddTicks(9125),
                            ManagerLevel = "1"
                        },
                        new
                        {
                            Id = 4,
                            Email = "4",
                            FirstName = "Denis",
                            LastName = "Music",
                            PasswordHash = new byte[] { 129, 239, 116, 26, 24, 102, 142, 194, 211, 49, 217, 207, 174, 123, 16, 237, 66, 195, 220, 119, 252, 39, 69, 15, 144, 124, 205, 16, 48, 150, 142, 35, 214, 217, 107, 175, 28, 38, 106, 76, 192, 179, 91, 14, 26, 5, 32, 80, 38, 247, 163, 124, 13, 130, 118, 90, 10, 214, 137, 189, 22, 241, 115, 49 },
                            PasswordSalt = new byte[] { 98, 172, 48, 116, 95, 203, 108, 1, 224, 199, 159, 129, 67, 46, 182, 136, 135, 198, 175, 247, 201, 53, 252, 123, 71, 147, 16, 112, 233, 11, 200, 201, 177, 173, 228, 141, 247, 166, 137, 19, 80, 64, 24, 235, 239, 140, 209, 171, 50, 67, 26, 43, 80, 69, 166, 148, 95, 129, 7, 240, 18, 133, 43, 33, 97, 55, 142, 184, 8, 123, 8, 169, 106, 216, 190, 27, 235, 105, 186, 234, 186, 35, 213, 55, 129, 102, 79, 201, 236, 125, 41, 11, 64, 120, 228, 95, 7, 164, 254, 143, 190, 114, 138, 53, 106, 200, 56, 79, 86, 96, 104, 109, 142, 181, 83, 33, 89, 193, 65, 14, 59, 87, 158, 243, 69, 106, 195, 201 },
                            TenantId = "bugojno",
                            Department = "IT",
                            HireDate = new DateTime(2024, 11, 25, 17, 31, 42, 138, DateTimeKind.Local).AddTicks(33),
                            ManagerLevel = "2"
                        });
                });

            modelBuilder.Entity("GPS.API.Data.Models.Passenger", b =>
                {
                    b.HasBaseType("GPS.API.Data.Models.MyAppUser");

                    b.Property<int?>("DiscountID")
                        .HasColumnType("int");

                    b.HasIndex("DiscountID");

                    b.ToTable("Passengers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 5,
                            Email = "5",
                            FirstName = "Adil",
                            LastName = "Joldic",
                            PasswordHash = new byte[] { 129, 239, 116, 26, 24, 102, 142, 194, 211, 49, 217, 207, 174, 123, 16, 237, 66, 195, 220, 119, 252, 39, 69, 15, 144, 124, 205, 16, 48, 150, 142, 35, 214, 217, 107, 175, 28, 38, 106, 76, 192, 179, 91, 14, 26, 5, 32, 80, 38, 247, 163, 124, 13, 130, 118, 90, 10, 214, 137, 189, 22, 241, 115, 49 },
                            PasswordSalt = new byte[] { 98, 172, 48, 116, 95, 203, 108, 1, 224, 199, 159, 129, 67, 46, 182, 136, 135, 198, 175, 247, 201, 53, 252, 123, 71, 147, 16, 112, 233, 11, 200, 201, 177, 173, 228, 141, 247, 166, 137, 19, 80, 64, 24, 235, 239, 140, 209, 171, 50, 67, 26, 43, 80, 69, 166, 148, 95, 129, 7, 240, 18, 133, 43, 33, 97, 55, 142, 184, 8, 123, 8, 169, 106, 216, 190, 27, 235, 105, 186, 234, 186, 35, 213, 55, 129, 102, 79, 201, 236, 125, 41, 11, 64, 120, 228, 95, 7, 164, 254, 143, 190, 114, 138, 53, 106, 200, 56, 79, 86, 96, 104, 109, 142, 181, 83, 33, 89, 193, 65, 14, 59, 87, 158, 243, 69, 106, 195, 201 },
                            TenantId = "mostar"
                        },
                        new
                        {
                            Id = 6,
                            Email = "6",
                            FirstName = "Denis",
                            LastName = "Music",
                            PasswordHash = new byte[] { 129, 239, 116, 26, 24, 102, 142, 194, 211, 49, 217, 207, 174, 123, 16, 237, 66, 195, 220, 119, 252, 39, 69, 15, 144, 124, 205, 16, 48, 150, 142, 35, 214, 217, 107, 175, 28, 38, 106, 76, 192, 179, 91, 14, 26, 5, 32, 80, 38, 247, 163, 124, 13, 130, 118, 90, 10, 214, 137, 189, 22, 241, 115, 49 },
                            PasswordSalt = new byte[] { 98, 172, 48, 116, 95, 203, 108, 1, 224, 199, 159, 129, 67, 46, 182, 136, 135, 198, 175, 247, 201, 53, 252, 123, 71, 147, 16, 112, 233, 11, 200, 201, 177, 173, 228, 141, 247, 166, 137, 19, 80, 64, 24, 235, 239, 140, 209, 171, 50, 67, 26, 43, 80, 69, 166, 148, 95, 129, 7, 240, 18, 133, 43, 33, 97, 55, 142, 184, 8, 123, 8, 169, 106, 216, 190, 27, 235, 105, 186, 234, 186, 35, 213, 55, 129, 102, 79, 201, 236, 125, 41, 11, 64, 120, 228, 95, 7, 164, 254, 143, 190, 114, 138, 53, 106, 200, 56, 79, 86, 96, 104, 109, 142, 181, 83, 33, 89, 193, 65, 14, 59, 87, 158, 243, 69, 106, 195, 201 },
                            TenantId = "sarajevo"
                        });
                });

            modelBuilder.Entity("GPS.API.Data.Models.Feedback", b =>
                {
                    b.HasOne("GPS.API.Data.Models.MyAppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GPS.API.Data.Models.Line", b =>
                {
                    b.HasOne("GPS.API.Data.Models.Station", "EndingStation")
                        .WithMany()
                        .HasForeignKey("EndingStationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GPS.API.Data.Models.Station", "StartingStation")
                        .WithMany()
                        .HasForeignKey("StartingStationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("EndingStation");

                    b.Navigation("StartingStation");
                });

            modelBuilder.Entity("GPS.API.Data.Models.Notification", b =>
                {
                    b.HasOne("GPS.API.Data.Models.Line", "Line")
                        .WithMany()
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GPS.API.Data.Models.NotificationType", "NotificationType")
                        .WithMany()
                        .HasForeignKey("NotificationTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Line");

                    b.Navigation("NotificationType");
                });

            modelBuilder.Entity("GPS.API.Data.Models.PassengerCreditCard", b =>
                {
                    b.HasOne("GPS.API.Data.Models.CreditCard", "CreditCard")
                        .WithMany()
                        .HasForeignKey("CreditCardId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GPS.API.Data.Models.Passenger", "Passenger")
                        .WithMany()
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreditCard");

                    b.Navigation("Passenger");
                });

            modelBuilder.Entity("GPS.API.Data.Models.Route", b =>
                {
                    b.HasOne("GPS.API.Data.Models.Line", "Line")
                        .WithMany()
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GPS.API.Data.Models.Station", "Station")
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Line");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("GPS.API.Data.Models.Schedule", b =>
                {
                    b.HasOne("GPS.API.Data.Models.Line", "Line")
                        .WithMany()
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Line");
                });

            modelBuilder.Entity("GPS.API.Data.Models.Shift", b =>
                {
                    b.HasOne("GPS.API.Data.Models.Bus", "Bus")
                        .WithMany()
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GPS.API.Data.Models.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Bus");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("GPS.API.Data.Models.Station", b =>
                {
                    b.HasOne("GPS.API.Data.Models.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("GPS.API.Data.Models.SystemActionLog", b =>
                {
                    b.HasOne("GPS.API.Data.Models.MyAppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GPS.API.Data.Models.Ticket", b =>
                {
                    b.HasOne("GPS.API.Data.Models.Line", "Line")
                        .WithMany()
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GPS.API.Data.Models.TicketType", "TicketType")
                        .WithMany()
                        .HasForeignKey("TicketTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GPS.API.Data.Models.MyAppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GPS.API.Data.Models.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Line");

                    b.Navigation("TicketType");

                    b.Navigation("User");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("GPS.API.Data.Models.Driver", b =>
                {
                    b.HasOne("GPS.API.Data.Models.MyAppUser", null)
                        .WithOne()
                        .HasForeignKey("GPS.API.Data.Models.Driver", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GPS.API.Data.Models.Manager", b =>
                {
                    b.HasOne("GPS.API.Data.Models.MyAppUser", null)
                        .WithOne()
                        .HasForeignKey("GPS.API.Data.Models.Manager", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GPS.API.Data.Models.Passenger", b =>
                {
                    b.HasOne("GPS.API.Data.Models.Discount", "Discount")
                        .WithMany()
                        .HasForeignKey("DiscountID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("GPS.API.Data.Models.MyAppUser", null)
                        .WithOne()
                        .HasForeignKey("GPS.API.Data.Models.Passenger", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discount");
                });
#pragma warning restore 612, 618
        }
    }
}
